version: '3.8'

services:
  zephyr_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    working_dir: /workspace/temp_udp_app
    command: ["./entrypoint.sh"]
    network_mode: "host"  # Use host network for UDP communication

networks:
  default:
    driver: bridge

volumes:
  workspace:
    driver: local
    